[package]
name = "VesperOS"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.5.0"
noto-sans-mono-bitmap = "0.3.1"

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
